trainer:
  max_epochs: 50
  precision: 16-mixed        #AMP
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "coco_to_cityscapes_finetune_head_only_fast"

# only class_head trained (with cached features for faster finetuning)

model:
  class_path: training.mask_classification_semantic.MaskClassificationSemantic
  init_args:
    attn_mask_annealing_enabled: false
    ckpt_path: weights/eomt_coco.bin
    load_ckpt_class_head: false

    freeze_all_except_class_head: true
    use_cached_features: true
    class_only_loss: true

    lr: 1e-4

    network:
      class_path: models.eomt_finetuning.EoMT     
      init_args:
        num_q: 200
        num_blocks: 3
        masked_attn_enabled: false
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_base_patch14_reg4_dinov2

data:
  class_path: datasets.cityscapes_semantic.CityscapesSemantic